### PR TITLE
Add favicon and Update dnnicon.html

### PR DESCRIPTION
**Pull request by amitsingh-24**
Merge this Pull Request to see favicon in website.

### CODE REVIEW

**Comment by valadas** [comment]
I am unfamiliar with this project, where does it get used?

**Comment by WillStrohl** [comment]
> I am unfamiliar with this project, where does it get used?

Uh...  Me too!  😁

**Comment by Timo-Breumelhof** [comment]
haha me too :-)

**Comment by WillStrohl** [comment]
As soon as any of us find out... We must update the README.  🤣

bitmoji

**Comment by david-poindexter** [comment]
This is not a valid PR - sorry.

image

**Comment by david-poindexter** [comment]
By the way, for all you DNN'ers - here is the GitHub Pages implementation of this repo - http://dnncommunity.github.io/dnnicons

**Comment by X3Technology** [comment]
Interesting. I see the repo was started by Joe Brinkman.  But I don’t know where this is used.  Was this intended for the PersonaBar maybe?

Is this something we need?  I could see the value in having a common font icon library just from a consistency perspective, but I’m not sure its worth it to maintain our own vs. just using a popular more mature one like FontAwesome or any of the others.

**Comment by david-poindexter** [comment]
@mathisjay I'm sure there were great intentions behind this project and it seemed like a cool idea at the time.  I actually remember with @jbrinkman presented the concept.  At the time though, many other icon libraries were evolving as so this project fizzled out.  With only 29 of the "hundreds of different icons" implemented, this would be a pretty huge undertaking for very little value at this point in my opinion.  There are many great free and commercial options that are super easy to integrate.  So, I'm not sure we should try to reinvent the wheel here.

**Comment by X3Technology** [comment]
I agree.  Lots of effort and only minimal benefit compared to using an existing font library.

Should this repo be retired?  Or at least remove 'the official' part from the description?

Sent via the Samsung Galaxy S20 5G, an AT&T 5G smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by david-poindexter** [comment]
@mathisjay that's a good question, and I'd love to say "yes".  However, it is actually already being used in DNN Platform.  😉

**Comment by X3Technology** [comment]
Sounds like a decision needs to be made to either suport this or remove it from platforn and retire it.   Perhaps for DNN10?

Sent via the Samsung Galaxy S20 5G, an AT&T 5G smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by david-poindexter** [comment]
I personally don't see this as a critical issue either way, but certainly someone can take it on (either way).  

It is consumed so lightly in DNN Platform at this point that it would be technically simple to remove.  However, in the off chance that someone has consumed/used this "feature" in their custom extension, then removing it from the platform would be a breaking change for them.  To remove it in v10, we would have to find a way to mark it deprecated in v9, but it is not 100% clear to me how we would do that since it is just a font with some supporting CSS, etc.

If you are interesting, here is where it is used in DNN Platform:
* https://github.com/dnnsoftware/Dnn.Platform/search?q=dnnicon
* https://github.com/dnnsoftware/Dnn.Platform/search?q=dnn-icon

**Comment by X3Technology** [comment]
I'd love to see v10 dump as much technical debt as possible.  If it is a breaking change, this would be the time to do it.

Sent via the Samsung Galaxy S20 5G, an AT&T 5G smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by david-poindexter** [comment]
If you have any ideas on how to mark it deprecated, I'm all ears.  😄  @mitchelsellers @valadas @bdukes @donker - thoughts?

**Comment by jncraig** [comment]
I agree that this is one of those little artifacts of DNN's past that
should be removed and replaced with something more appropriate and in an
appropriate standards-based way.

The fact that most people weren't even aware of its existence as a project
is all that we really need to say.

**Comment by jbrinkman** [comment]
Just as some history, this was originally intended for the personabar.  We were embedding lots of little SVG files into the project for the various icons, which meant lots of extra HTTP calls.  The intent was to have a single set of font icons that could be maintained as a family of icons.  It was never intended as an alternative to Fontawesome or any other font icon pack, but just a management tool since we were using lots of custom svg icons in the project and it kept growing.

**Comment by amitsingh-24** [comment]
Why you are not merging my pull request. this is very important for me and please accept this request and add "hacktoberfest-accepted" tag.

**Comment by mitchelsellers** [comment]
Given the limited usage and the fact that this is another “internal” item that could have been used by others. I think we document this, and remove it in 10.x. 

There isn’t a method to easily mark obsolete so we will have to just document. 

@amitsingh-24 this PR was closed as the change does not further the project or match the actual logo branding

**Pull request closed without merging**
